name: hello world workflow


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      # another step with a shell command
      - name: hello world
        run: echo "Hello world 2!"
        shell: bash

  # another job echoing goodbte world 
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world!"
        shell: bash

 